### ISSUE TITLE
Unexpected character '�'

### ISSUE THREAD

**Issue by asterikx** [pilcrowOnPaper/oslo#43]
I get the following error in a SolidStart project (i.e. using Vite) after upgrading to `oslo@1.1.0`:

```
[commonjs--resolver] Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
file: /Users/erikmuller/cn-webapp/node_modules/@node-rs/argon2/index.js:1:0
1: ����
       ���__TEXT@__text...
   ^
2: �H__LINKEDIT�
�/Users/runner/work/node-rs/node-rs/target/aarch6...

[12:36:09 AM]  ERROR  Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)

  at error (node_modules/vinxi/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (node_modules/vinxi/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
  at Module.tryParse (node_modules/vinxi/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:14476:25)
  at Module.setSource (node_modules/vinxi/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:14077:39)
  at ModuleLoader.addModuleSource (node_modules/vinxi/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24649:20)
```

The issue has also been reported for SvelteKit project [here](https://discord.com/channels/1004048134218981416/1205198828052025454/1205198828052025454) and the resolution proposed in [this post](https://discord.com/channels/1004048134218981416/1201081039628533810/1201542701326278767) doesn't work for me.

**Comment by pilcrowonpaper** [comment]
Did you install it as a dev dependency?

**Comment by asterikx** [comment]
No, I installed `oslo@1.1.1` as a regular dependency.

**Comment by pilcrowonpaper** [comment]
Can you try the solution in the Vite section?
https://lucia-auth.com/getting-started/#vite

**Comment by v-morlock** [comment]
the solution described in the vite section doesn't solve this for me

**Comment by pilcrowonpaper** [comment]
Closing this due to a lack of activity
